#pragma once

#include "common.h"
#include "texture.h"

struct Glyph {
	int u;
	int v;
	int width;
	int height;
	int xoffset;
	int yoffset;
	int xadvance;
};

struct Font {
	Texture atlas;
	bool should_free_atlas;

	array<Glyph> glyphs; // [32..126]
	bool should_free_glyphs;

	int size;
	int line_height;
};

enum HAlign {
	HALIGN_LEFT,
	HALIGN_CENTER,
	HALIGN_RIGHT,
};

enum VAlign {
	VALIGN_TOP,
	VALIGN_MIDDLE,
	VALIGN_BOTTOM,
};

// load files generated by AngelCode's BMFont.
bool load_bmfont_file(Font* f, const char* fnt_filepath, const char* png_filepath);

// Monospace.
bool load_font_from_texture(Font* f, const Texture& texture,
							int size, int line_height, int char_width,
							int xoffset, int yoffset);

void free_font(Font* f);

// Returns the position of the next-to-be-drawn character.
// No Unicode, only Ascii.
vec2 draw_text(Font font, string text, vec2 text_pos,
			   HAlign halign = HALIGN_LEFT, VAlign valign = VALIGN_TOP, vec4 color = color_white);

vec2 draw_text_shadow(Font font, string text, vec2 text_pos,
					  HAlign halign = HALIGN_LEFT, VAlign valign = VALIGN_TOP, vec4 color = color_white);

// The height of an empty string is font.size
vec2 measure_text(Font font, string text, bool only_one_line = false);
